
ARCPATH = ../../_arch

ARC = D:/Programs/7za/7za.exe

ARCFILTER = Makefile *.awl *.log *.rsp

arc:
	$(ARC) a $(ARCPATH)/_tests_math $(ARCFILTER)

tarc:
	$(ARC) t $(ARCPATH)/_tests_math.7z

wc:
	wc *.c *.cpp *.h *.l *.y

