
ARCPATH = ../../_arch

ARC = D:/Programs/7za/7za.exe

ARCFILTER = Makefile *.awl *.log

arc:
	$(ARC) a $(ARCPATH)/_tests_spec $(ARCFILTER)
tarc:
	$(ARC) t $(ARCPATH)/_tests_spec.7z

wc:
	wc *.c *.cpp *.h *.l *.y

